apiVersion: v1
kind: ConfigMap
metadata:
  name: feedback-service-config
data:
  SERVER_PORT: "9004"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.ybrainy.svc.cluster.local:3306/feedback_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  YBRAINY_EUREKA_URL: "http://eureka-server.ybrainy.svc.cluster.local:8761/eureka/"
  SPRING_RABBITMQ_HOST: "rabbitmq.ybrainy.svc.cluster.local"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "guest"
  ZIPKIN_URL: "http://zipkin.ybrainy.svc.cluster.local:9411"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_METRICS_TAGS_APPLICATION: "feedback-service"
