apiVersion: v1
kind: Secret
metadata:
  name: feedback-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "rootpass"
  SPRING_RABBITMQ_PASSWORD: "guest"
  HUGGINGFACE_API_TOKEN: "replace-me"
