apiVersion: v1
kind: Secret
metadata:
  name: inscription-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "rootpass"
  SPRING_MAIL_PASSWORD: "replace-me"
