server.port=8888
spring.application.name=config-server

# Eureka
eureka.client.service-url.defaultZone=${YBRAINY_EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Use native file system as config source (no Git needed)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config

# Allow all services to fetch config
spring.cloud.config.server.accept-empty=true
