apiVersion: v1
kind: Secret
metadata:
  name: event-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "rootpass"
  EVENT_GROQ_API_KEY: "replace-me"
  HF_TOKEN: "replace-me"
  GITHUB_MODELS_API_KEY: "replace-me"
